[features]
seeds = false
skip-lint = false
[programs.devnet]
fungible_token = "J6FNyPbxSfDuCUSZ3HtEqx1KzawNw1T1QiMjxW9KjPwK"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/codezeros/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
